all:
  hosts:
    k8s-master-1:
      ansible_host: 178.154.229.101
      ip: 10.10.0.22
      access_ip: 178.154.229.101
    k8s-worker-1:
      ansible_host: 158.160.78.159
      ip: 10.20.0.30
      access_ip: 158.160.78.159
    k8s-worker-2:
      ansible_host: 158.160.193.218
      ip: 10.30.0.25
      access_ip: 158.160.193.218

  children:
    kube_control_plane:
      hosts:
        k8s-master-1:
    kube_node:
      hosts:
        k8s-worker-1:
        k8s-worker-2:
    etcd:
      hosts:
        k8s-master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
